language: java
jdk:
  - openjdk11

cache:
  directories:
  - $HOME/.m2/repository/

sudo: required

services:
  - docker
before_install:
  - chmod +x gradlew
  - docker pull oracle/graalvm-ce:1.0.0-rc8