version: '2'

services:
  mysql-service:
    image: mysql:latest
    container_name: test-mysql
    ports:
    - 6603:3306
    env_file:
    - .env
    volumes:
    - /storage/docker/mysql-datadir:/var/lib/mysql
  codecrusade-service:
    env_file:
    - .env
    build:
      dockerfile: Dockerfile
      context: ./application
    depends_on:
    - mysql-service
    ports:
    - 8080:8080
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-service:3306
  eureka:
    image: netflixoss:eureka
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8070/eureka/
    tty: false
    ports:
    - 8070:8070