version: '2'

services:
  mysql-service:
    image: mysql:latest
    ports:
    - 6603:3306
    env_file:
    - .env
    volumes:
    - /storage/docker/mysql-datadir:/var/lib/mysql
  eureka-service:
    build:
      dockerfile: Dockerfile
      context: ./eureka-service
    environment:
      - EUREKA_URI=http://eureka-service:8282/eureka/
    tty: false
    ports:
      - 8282:8282
  config-server:
    build:
      dockerfile: Dockerfile
      context: ./config-server
    ports:
      - 9999:9999
    depends_on:
    - eureka-service
    environment:
    - EUREKA_URI=http://eureka-service:8282/eureka
  zuul-gateway:
    build:
      dockerfile: Dockerfile
      context: ./zuul-gateway
    ports:
    - 8443:8443
    depends_on:
    - eureka-service
    - config-server
    environment:
      - CONFIG_SERVER_URI=http://config-server:9999
      - EUREKA_URI=http://eureka-service:8282/eureka
    links:
      - eureka-service
      - codecrusade-service
  codecrusade-service:
    env_file:
    - .env
    build:
      dockerfile: Dockerfile
      context: ./application
    depends_on:
    - mysql-service
    - eureka-service
    ports:
    - 8181:8181
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-service:3306/${MYSQL_DATABASE}
      - CONFIG_SERVER_URI=http://config-server:9999
      - EUREKA_URI=http://eureka-service:8282/eureka
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}


