spring:
  liquibase:
    change-log: classpath:db/main.xml
    enabled: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        id:
          new_generator_mappings: false

jwt:
  header: Authorization
