spring:
  liquibase:
    change-log: classpath:db/main.xml
  datasource:
    url: jdbc:h2:~/db/codecrusade-dev;MODE=MYSQL
    username: sa
    password:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        id:
          new_generator_mappings: false
