server:
  port: 8080

spring:
  application:
    name: zuul-gateway
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:9999}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8282/eureka}